CREATE VIEW V_MARKS AS SELECT ROLLNO,NAME,SUB_CODE,MARKS FROM RESULT INNER JOIN STUDENT ON ROLL_NO=ROLLNO WHERE DEPTCODE='CSE';

CREATE VIEW V_CLASSTAKEN AS SELECT SUBJECTCODE,SUBJECTNAME,FID,NAME FROM SUBJECT INNER JOIN FACULTY ON FID=TEACHER;

CREATE VIEW V_SUBJECT AS SELECT SUBJECTCODE,SUBJECTNAME,NAME FROM SUBJECT,(SELECT SUB_CODE,COUNT(SUB_CODE) AS SUB_COUNT FROM RESULT GROUP BY SUB_CODE),FACULTY WHERE SUB_COUNT>1 AND SUB_CODE=SUBJECTCODE AND FID=TEACHER;

CREATE VIEW V_STUDENT AS SELECT NAME,ROLL_NO,DEPTCODE FROM STUDENT WHERE ROLL_NO IN (SELECT ROLLNO FROM RESULT);

CREATE VIEW V_DEPT AS SELECT DEPTCODE,SEMESTER,COUNT(DISTINCT(ROLLNO)) AS STUD_COUNT FROM SUBJECT,RESULT WHERE MARKS>75 GROUP BY(DEPTCODE,SEMESTER);
