ALTER TABLE STUDENT ADD FOREIGN KEY(DEPTCODE) REFERENCES DEPARTMENT(DEPTCODE);

SELECT CONSTRAINT_NAME,SEARCH_CONDITION, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='STUDENT';

SELECT CONSTRAINT_NAME,SEARCH_CONDITION, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME='DEPARTMENT';

ALTER TABLE DEPARTMENT ADD(BLOCK CHAR(2));

UPDATE DEPARTMENT SET BLOCK='C' WHERE DEPTCODE='CSE' OR DEPTCODE='IT';

UPDATE DEPARTMENT SET BLOCK='B' WHERE DEPTCODE='ECE' OR DEPTCODE='EE'; 

alter table subject modify(subjectcode Varchar2(8));

ALTER TABLE SUBJECT DROP CONSTRAINT SYS_C004104;

ALTER TABLE SUBJECT ADD CONSTRAINT PK1234 PRIMARY KEY(SUBJECTCODE);

ALTER TABLE RESULT ADD FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUBJECTCODE);

ALTER TABLE RESULT ADD CONSTRAINT A1234 CHECK (MARKS>=0);

ALTER TABLE DEPARTMENT ADD CONSTRAINT B1234 CHECK(DEPTCODE='CSE' OR DEPTCODE='IT' OR DEPTCODE='MCA' OR DEPTCODE='EE' OR DEPTCODE='ECE');

ALTER TABLE STUDENT ADD(COLLEGEPHONENO NUMBER(8));

UPDATE STUDENT SET COLLEGEPHONENO=25739607;

CREATE TABLE FACULTY (FID VARCHAR2(4), NAME VARCHAR2(20) NOT NULL, CHECK (FID LIKE 'F%'));

INSERT INTO FACULTY VALUES('F01','Aloke Kumar Dutta');
INSERT INTO FACULTY VALUES('F02','Abhijit Roy');
INSERT INTO FACULTY VALUES('F03','Probal Kumar');
INSERT INTO FACULTY VALUES('F04','Mousumi Dey');
INSERT INTO FACULTY VALUES('F05','Sharmistha Nag');
INSERT INTO FACULTY VALUES('F06','Dipti Bhattacharya');
INSERT INTO FACULTY VALUES('F07','Sanjay Kumar Das');
INSERT INTO FACULTY VALUES('F08','Partha Pratim Ba');
INSERT INTO FACULTY VALUES('F09','Rakesh Chouhan');
INSERT INTO FACULTY VALUES('F10','Srija Paul');

ALTER TABLE SUBJECT ADD (PASSMARKS NUMBER(2));

SELECT * FROM SUBJECT;
UPDATE SUBJECT SET PASSMARKS=40;

ALTER TABLE RESULT DROP COLUMN PASSMARKS;
