select name,phoneno from STUDENT,RESULT WHERE STUDENT.NAME LIKE '_a%' AND RESULT.SUB_CODE='CS301' AND STUDENT.ROLLNO=RESULT.ROLLNO;

SELECT RESULT.ROLLNO,SUB_CODE,MARKS FROM RESULT,STUDENT WHERE MONTH(BIRTHDATE)=06 AND STUDENT.ROLLNO=RESULT.ROLLNO;

SELECT * FROM STUDENT WHERE SEMESTER='SEM5' AND DEPTCODE='CSE';

SELECT * FROM SUBJECT WHERE SUBJECTCODE LIKE 'CS3%';

SELECT NAME,DEPTNAME FROM STUDENT,RESULT,DEPARTMENT WHERE MARKS>90 AND STUDENT.ROLLNO=RESULT.ROLLNO AND STUDENT.DEPTCODE=DEPARTMENT.DEPTCODE;

SELECT DISTINCT(NAME) FROM RESULT,STUDENT WHERE SUB_CODE LIKE '%5%' AND MARKS>80 AND STUDENT.ROLLNO=RESULT.ROLLNO;

SELECT NAME FROM RESULT,STUDENT WHERE STUDENT.DEPTCODE='CSE' AND MARKS>80 AND SUB_CODE='CS301' AND YEAR(BIRTHDATE)=2000 AND STUDENT.ROLLNO=RESULT.ROLLNO;

SELECT DEPARTMENT.* FROM SUBJECT,DEPARTMENT WHERE STUDENT_ALLOTTED>80 AND SUBJECT.SUBJECTNAME='Intelligent Systems' AND DEPARTMENT.DEPTCODE=SUBJECT.DEPTCODE;

SELECT SUBJECTCODE,SUBJECTNAME FROM SUBJECT,DEPARTMENT WHERE STUDENT_ALLOTTED<100 AND SUBJECT.DEPTCODE=DEPARTMENT.DEPTCODE;

SELECT ROLLNO, SUB_CODE,mARKS FROM RESULT,SUBJECT WHERE SEMESTER='SEM5' AND SUBJECTNAME LIKE 'D%' AND SUBJECT.SUBJECTCODE=RESULT.SUB_CODE;

SELECT RESULT.ROLLNO, SUB_CODE,mARKS FROM RESULT,STUDENT WHERE SUB_CODE='CS505' AND YEAROFADM=2017 AND RESULT.ROLLNO=STUDENT.ROLLNO;

SELECT SUBJECTCODE,SUBJECTNAME FROM SUBJECT WHERE SUBJECT.SUBJECTCODE NOT IN (SELECT SUB_CODE FROM RESULT);

SELECT * FROM STUDENT WHERE ROLLNO NOT IN (SELECT ROLLNO FROM RESULT) AND DEPTCODE='CSE';
